# Generated by Django 4.2.5 on 2024-01-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_article_sub_text_article_user_manual_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='orderx',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='ordery',
            field=models.IntegerField(default=0),
        ),
    ]
