# Generated by Django 4.2.5 on 2024-01-27 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('terms', models.IntegerField()),
                ('visits', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Draft', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('icase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.icase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreatPlanDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodypart', models.CharField(max_length=100)),
                ('treatmentcode', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('unitprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxcode', models.CharField(max_length=100)),
                ('taxrate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sortingorder', models.IntegerField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icases.treatplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
