# Generated by Django 4.2.5 on 2024-01-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icases', '0002_treatplan_treatplandetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icase',
            name='category',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Big', 'Big')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='icase',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Processing', 'Processing'), ('Closed', 'Closed')], default='Draft', max_length=100),
        ),
    ]
